In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import io

In [2]:
from google.colab import files
uploaded = files.upload()

Saving dataset_with_target.csv to dataset_with_target.csv


In [0]:
dataset = pd.read_csv("dataset_with_target.csv",encoding='windows-1254') 

In [4]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [0]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [6]:
dataset.shape

(633, 6)

In [7]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 633 entries, 0 to 632
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  633 non-null    int64  
 1   Date        633 non-null    object 
 2   Tweet       633 non-null    object 
 3   Open        633 non-null    float64
 4   Close       633 non-null    float64
 5   inc_dec     633 non-null    int64  
dtypes: float64(2), int64(2), object(2)
memory usage: 29.8+ KB


In [0]:
new_tweet = []
for i in range(0, 633):
  tweet = re.sub('[^a-zA-Z]', ' ', dataset['Tweet'][i])
  tweet = tweet.lower()
  tweet = tweet.split()
  ps = PorterStemmer()
  tweet = [ps.stem(word) for word in tweet if not word in set(stopwords.words('english'))]
  tweet = ' '.join(tweet)
  new_tweet.append(tweet)

In [11]:
print(new_tweet)

['rt jonfavreau model arriv went electr like dylan ff teslamotor elonmusk', 'return trip london oxford met mani interest peopl realli like britain', 'articl space news describ arian vs httptcoiaeyxxk httptcogh fg wbtw dont think appl doom wont unseat googl st place larri p charg httptcohsiaekawwa misquot bbc say europ rocket chanc said francogerman arian chanc go arian yousrc amoss articl fair editor chose sensat headlin use quot even though didnt actual say thatmass judg deni auto dealer demand kill littl tesla store yay justic prevail httptcomqnnysc', 'love pictur curious rover mar landscap look like california desert httptco gdasaert westcoastbil hello wire break possibl nasa curios rover found organ molecul mar httptcom thomastregn exactli', 'liam neeson life short sketch super funni httptconql wox talk royal aeronaut societi onlin get littl technic httptcozmbkc jh', 'human wish becom multiplanet speci must figur move million peopl marsmillion peopl need mar coloni k would number m

In [12]:
len(new_tweet)

633

In [0]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1000)
X = cv.fit_transform(new_tweet).toarray()
y = dataset.iloc[:, -1].values

In [77]:
X.shape

(633, 1000)

In [0]:
df = pd.DataFrame(X) 

In [0]:
df.to_csv('newdata_with_target.csv')

In [80]:
pd.read_csv('newdata_with_target.csv')

Unnamed: 0  0  1  2  3  4  5  6  ...  992  993  994  995  996  997  998  999
0             0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
1             1  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
2             2  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
3             3  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
4             4  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
..          ... .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...
628         628  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
629         629  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
630         630  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
631         631  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
632         632  0  0  1  0  0  0  0  ...    0    0    0    0    0    1    0    0

[633 rows x 1001 columns]

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.10, random_state = 0)

In [89]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [0]:
y_pred = classifier.predict(X_test)

In [57]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [0 1]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 1]
 [1 1]
 [0 1]
 [0 1]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [0 0]
 [1 1]
 [1 0]
 [1 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 1]
 [1 0]
 [1 1]
 [0 1]
 [1 1]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]]


In [68]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[17, 34],
       [27, 49]])

In [69]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.5196850393700787

In [0]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score 
model_one = LogisticRegression()


In [92]:
model_one.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
y_pred_one = model_one.predict(X_test)

In [94]:
print(np.concatenate((y_pred_one.reshape(len(y_pred_one),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 0]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [0 0]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [0 1]
 [1 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 1]]


In [95]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred_one)

array([[12,  9],
       [21, 22]])

In [96]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred_one)

0.53125